language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION='2.3.*' FOSUSERBUNDLE_VERSION='~1.2'
  - SYMFONY_VERSION='2.4.*' FOSUSERBUNDLE_VERSION='~1.2'
  - SYMFONY_VERSION='2.3.*' FOSUSERBUNDLE_VERSION='2.0.*@dev'
  - SYMFONY_VERSION='2.4.*' FOSUSERBUNDLE_VERSION='2.0.*@dev'
  - SYMFONY_VERSION='2.5.*' FOSUSERBUNDLE_VERSION='2.0.*@dev'

before_script:
    - composer require --no-update symfony/symfony=${SYMFONY_VERSION}
    - composer require --no-update friendsofsymfony/user-bundle=${FOSUSERBUNDLE_VERSION}
    - composer install --prefer-source --no-interaction

script: bin/phpunit --coverage-clover=coverage.clover --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
